/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolist.view;

import com.mycompany.todolist.controller.ControllerUsuario;
import com.mycompany.todolist.model.Usuario;
import com.mycompany.todolist.util.InicializarComponentes;
import com.mycompany.todolist.util.ValidaCampos;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastroUsuario extends javax.swing.JFrame {

    private ArrayList<Usuario> listaDeUsuario = new ArrayList<>();
    private final InicializarComponentes ic = new InicializarComponentes();
    
    private final String NOME_USUARIO = "Digite seu nome";
    private final String EMAIL_USUARIO = "Digite seu email";
    private final String SENHA_USUARIO = "Digite sua senha";
    private final String CONFIRMAR_SENHA = "Confirme sua senha";
    private ValidaCampos validaCampos = new ValidaCampos();
    
    public CadastroUsuario() {
        initComponents();
        setLocationRelativeTo(this);
        configuraCampos();
    }
    
    public CadastroUsuario(ArrayList<Usuario> listaDeUsuario){
        initComponents();
        this.listaDeUsuario = listaDeUsuario;
        setLocationRelativeTo(this);
        configuraCampos();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        psfSenha = new javax.swing.JPasswordField();
        psfConfirmaSenha = new javax.swing.JPasswordField();
        cbxMostrarSenhas = new javax.swing.JCheckBox();
        lblError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblErrorSenhas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 250, 248));

        txtNomeCompleto.setBackground(new java.awt.Color(249, 250, 248));
        txtNomeCompleto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome completo"));

        txtEmail.setBackground(new java.awt.Color(249, 250, 248));
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        psfSenha.setBackground(new java.awt.Color(249, 250, 248));
        psfSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Crie uma senha"));

        psfConfirmaSenha.setBackground(new java.awt.Color(249, 250, 248));
        psfConfirmaSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirme a senha"));

        cbxMostrarSenhas.setBackground(new java.awt.Color(249, 250, 248));
        cbxMostrarSenhas.setText("Mostrar senhas");
        cbxMostrarSenhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMostrarSenhasActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cadastro");

        btnCadastrar.setBackground(new java.awt.Color(249, 250, 248));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblErrorSenhas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(88, 88, 88))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblErrorSenhas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxMostrarSenhas)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(lblError)))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(psfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(psfConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMostrarSenhas)
                    .addComponent(lblErrorSenhas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblError)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(validaCampos()){
        Usuario user  = retornaUsuario();
        listaDeUsuario.add(user);
        new Login(listaDeUsuario).setVisible(true);
        this.dispose();

        }else{
            lblError.setForeground(Color.red);
            lblError.setText("Confira o preenchimento dos campos!");
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbxMostrarSenhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMostrarSenhasActionPerformed
        String senha =  String.valueOf(psfSenha.getPassword());
        String confirmarSenha = String.valueOf(psfConfirmaSenha.getPassword());
        ic.configCheckBox(cbxMostrarSenhas, psfSenha, SENHA_USUARIO, senha );
        ic.configCheckBox(cbxMostrarSenhas, psfConfirmaSenha, CONFIRMAR_SENHA, confirmarSenha  );
        
    }//GEN-LAST:event_cbxMostrarSenhasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JCheckBox cbxMostrarSenhas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblErrorSenhas;
    private javax.swing.JPasswordField psfConfirmaSenha;
    private javax.swing.JPasswordField psfSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCompleto;
    // End of variables declaration//GEN-END:variables

    private Usuario retornaUsuario(){
        Usuario u = new Usuario();
        
        String nome = txtNomeCompleto.getText();
        String email = txtEmail.getText();
        String senha = String.valueOf(psfSenha.getText());
        
        u.setNomeCompleto(nome);
        u.setEmail(email);
        u.setSenha(senha);
        
        return u;
    }
    
   private void configuraCampos(){
        ic.configuraTextField(txtNomeCompleto, NOME_USUARIO);
        ic.configuraTextField(txtEmail, EMAIL_USUARIO);
        ic.configCampoSenha(psfSenha, SENHA_USUARIO);
        ic.configCampoSenha(psfConfirmaSenha, CONFIRMAR_SENHA);
    }
   
   private boolean validaCampos(){
       boolean resultado = true;
       
       if(validaCampos.validaPasswordField(psfSenha, SENHA_USUARIO)) resultado = false;
       if(validaCampos.validaTextField(txtEmail, EMAIL_USUARIO)) resultado = false;
       if(validaCampos.validaTextField(txtNomeCompleto, NOME_USUARIO)) resultado = false;
       if(validaCampos.validaPasswordField(psfConfirmaSenha, CONFIRMAR_SENHA)) resultado = false;
       
       String senha = String.valueOf(psfSenha.getPassword());
       String confirmarSenha = String.valueOf(psfConfirmaSenha.getPassword());
       
       if(!senha.equals(confirmarSenha)) {
            lblErrorSenhas.setForeground(Color.red);
            lblErrorSenhas.setText("Senhas não coicidem!");
            resultado = false;
        }
       
       return resultado;
   }
}


